Fix aiohttp_asgi with aiohttp>=3.10.6...
mosquito/aiohttp-asgi pull request #11
Opened 2024-11-06 13:47 UTC by meyerj

... with https://github.com/aio-libs/aiohttp/pull/9200, and forward websocket subprotocols from the request headers.

I probably shouldn't have mixed these two things, but this version works for me with
```
aiohttp==3.10.9
channels==4.1.0
Django==4.2.16
```
to run a [Django](https://www.djangoproject.com/) application with [Channels](https://channels.readthedocs.io/en/latest/) and web sockets as an `ASGIResource` from an aiohttp application.

From [aiohttp/CHANGES.rst](https://github.com/aio-libs/aiohttp/blob/master/CHANGES.rst#removals-and-backward-incompatible-breaking-changes-1):

> Improved middleware performance -- by [:user:`bdraco`](https://github.com/aio-libs/aiohttp/blob/master/CHANGES.rst#id222).
> 
> The `set_current_app` method was removed from `UrlMappingMatchInfo` because it is no longer used, and it was unlikely external caller would ever use it.
> 
> Related issues and pull requests on GitHub: [:issue:`9200`](https://github.com/aio-libs/aiohttp/blob/master/CHANGES.rst#id224).

Likely the changes are not backwards compatible to older versions of aiohttp as-is...

2025-04-24 13:04 UTC, elthariel commented
Fixed the issue for me

2025-04-24 13:07 UTC, mosquito requested changes

2025-04-24 13:07 UTC, mosquito commented on aiohttp_asgi/resource.py
> +    # @contextmanager
let's mark it deprecated and call `self.add_app` under the hood

2025-05-02 19:00 UTC, meyerj commented on aiohttp_asgi/resource.py
> +    # @contextmanager
Something like in https://github.com/mosquito/aiohttp-asgi/pull/11/commits/0d4bd1d095d3c714863bf1fb7fd4822efbba5e2a?

2025-05-02 19:05 UTC, meyerj commented on aiohttp_asgi/resource.py
> +    # @contextmanager
`add_app()` does not overwrite the `current_app` property if one was already set before, which would be contradicting the purpose of the context manager, if I am not mistaken. So I also added a setter for `self._current_app` again in https://github.com/mosquito/aiohttp-asgi/pull/11/commits/de4826c85f44d71f71ff920677f2b7ef6724ea2c.

2025-06-10 10:04 UTC, mosquito approved these changes

2025-06-10 10:24 UTC, merged